services:
  app:
      image: dunglas/frankenphp
      container_name: dti-app
      volumes:
        - ./:/app
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
      ports:
        - 8000:8000
      tty: true
      environment:
        - SERVER_NAME=:8000
      networks:
        - dti
  mariadb:
    image: mariadb:latest
    container_name: dti-mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./database:/database
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      dti:
        ipv4_address: 10.255.255.99
  phpmyadmin:
    container_name: dti-phpmyadmin
    depends_on:
      - mariadb
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: '2048M'
    networks:
      - dti
  build:
    image: node:20-alpine
    container_name: dti-build
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ["npm","run", "dev"]
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1
    networks:
      - dti

volumes:
  mariadb: 
    driver: local
  postgres:
    driver: local

networks:
  dti:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.255.255.0/24
            gateway: 10.255.255.1
